### PR TITLE
Fixing some dependencies, adding CFC and Age examples, adding CFC data 

### PR DESCRIPTION
**Pull request by anthony-meza**
I installed a fresh fork of TMITransient.jl. I ran into some dependency issues involving the Differential Equations package. I also added two examples which (I think) simulate the circulation of an evolving CFC and Age-like boundary condition. These scripts plot the propagation of these tracers using the plotting scripts used in ex.1

### CODE REVIEW

**Review by ggebbie — CHANGES_REQUESTED** [review]
Thanks a lot, Anthony!  Looking like a nice contribution. Here are some questions to consider.

1. What does DrWatson help with? Because this is a numerically intensive package that is a dependency for other packages, I don't want to add DrWatson unless it does something you can't otherwise do.

2. The environment was pinned to an old version of the DifferentialEquations due to numerical problems. Please see Issues #26  and #17. Are these problems now solved?
https://github.com/ggebbie/TMItransient.jl/issues/17
https://github.com/ggebbie/TMItransient.jl/issues/26

3. The CFC and age tracer simulations are great additions! Note that the CFC simulation should have a Robin boundary condition, not a Dirichlet boundary condition. There isn't an easy to do this with TMI right now (I don't think), but it is worth adding some comments to this effect.

4. Regarding the scripts environment, please see https://github.com/ggebbie/TMItransient.jl/issues/13 for a justification.

**Comment by ggebbie** [comment]
Looks like the package is broken due to `GLMakie`. See the automated tests here: 
https://github.com/ggebbie/TMItransient.jl/actions/runs/10101275206/job/28125724067?pr=27

The TMItransient environment will ideally not have any plotting routines that are slow to compile. They can go in the scripts environment, if needed.

**Comment by ggebbie** [comment]
Numerical tests all pass!! This seems to be evidence that the issue #26 can be freed.

**Comment by ggebbie** [comment]
Can we do anything about the GLMakie error?  I authorized the automated tests and the error from above still exists. Can we remove GLMakie?

https://github.com/ggebbie/TMItransient.jl/actions/runs/10286321861/job/28467141448#step:6:467

**Comment by anthony-meza** [comment]
Ah yes, we can remove GLMakie. I'll do that now

**Comment by anthony-meza** [comment]
removed GLMakie, hope nothing else changed!

**Comment by ggebbie** [comment]
Thanks for removing `GLMakie`: the error is resolved now!

The title says that the dependencies are updated but OrdinaryDiffEq is still pinned to an old version. Is this what you intended?

https://github.com/ggebbie/TMItransient.jl/actions/runs/10286894472/job/28469504559#step:6:50

**Comment by ggebbie** [comment]
Please advise regarding items 2 and 3 (including `OrdinaryDiffEq` version) above. Thanks! It would be great to resolve this before we forget about it.

**Comment by anthony-meza** [comment]
Regarding #26 (item2) I did not need to update DifferentialEquations to get my code working, so I think that ODE can stay pinned for now. 

Regarding Item 3, I just added a comment in the CFC file specifying that we should have a Robin boundary condition in the future and the current script actually uses a Dirichlet boundary condition. 

Once this most recent commit passes all the checks, I think it's ready to merge!

**Review by ggebbie — APPROVED** [review]

**Pull request merged**
